// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Passkeys__AuthController from "./passkeys/auth_controller"
application.register("passkeys--auth", Passkeys__AuthController)

import Passkeys__LoginController from "./passkeys/login_controller"
application.register("passkeys--login", Passkeys__LoginController)

import Passkeys__RegisterController from "./passkeys/register_controller"
application.register("passkeys--register", Passkeys__RegisterController)
